#############
# BM via YAML
#############

>ocp-bm5-master01
HOST_INVENTORY=bm5-sno01
HOST_INVENTORY_LOCATION=enclosure-c7000
HOST_INVENTORY_NETWORKTYPE=dhcp

BARE_METAL_HOST=ocp-bm5-master01

BARE_METAL_BMC_IP=10.11.14.203

BARE_METAL_NETWORK_PROVISION_IP=DHCP
BARE_METAL_NETWORK_PROVISION_INT='eno49'
BARE_METAL_NETWORK_PROVISION_MAC='5E:2C:4A:50:03:49'

BARE_METAL_NETWORK_WORKLOAD_IP='10.6.82.39'
BARE_METAL_NETWORK_WORKLOAD_INT='eno50'
BARE_METAL_NETWORK_WORKLOAD_MAC='5E:2C:4A:50:03:4A'

CLUSTER=bm5-sno01

>ocp-bm5-master02
HOST_INVENTORY=bm5-sno02
HOST_INVENTORY_LOCATION=enclosure-c7000
HOST_INVENTORY_NETWORKTYPE=static

BARE_METAL_HOST=ocp-bm5-master02

BARE_METAL_BMC_IP=10.11.14.211

BARE_METAL_NETWORK_PROVISION_IP=DHCP
BARE_METAL_NETWORK_PROVISION_INT='eno49'
BARE_METAL_NETWORK_PROVISION_MAC='5E:2C:4A:50:03:4D'

BARE_METAL_NETWORK_WORKLOAD_IP='10.6.82.152'
BARE_METAL_NETWORK_WORKLOAD_INT='eno50'
BARE_METAL_NETWORK_WORKLOAD_MAC='5E:2C:4A:50:03:4E'

CLUSTER=bm5-sno02


>ocp-bm5-master03
HOST_INVENTORY=bm5-sno03
HOST_INVENTORY_LOCATION=enclosure-c7000
HOST_INVENTORY_NETWORKTYPE=static

BARE_METAL_HOST=ocp-bm5-master03

BARE_METAL_BMC_IP=10.11.14.205

BARE_METAL_NETWORK_PROVISION_IP=DHCP
BARE_METAL_NETWORK_PROVISION_INT='eno49'
BARE_METAL_NETWORK_PROVISION_MAC='5E:2C:4A:50:03:4B'

BARE_METAL_NETWORK_WORKLOAD_IP='10.6.82.153'
BARE_METAL_NETWORK_WORKLOAD_INT='eno50'
BARE_METAL_NETWORK_WORKLOAD_MAC='5E:2C:4A:50:03:4C'

CLUSTER=bm5-sno03


> Delete

oc project ${CLUSTER}
oc delete ManagedCluster ${CLUSTER}
oc delete AgentClusterInstall ${CLUSTER}
oc delete ClusterDeployment ${CLUSTER}
oc delete BareMetalHost ${BARE_METAL_HOST}
oc delete project ${CLUSTER}
# oc api-resources --verbs=list --namespaced -o name | xargs -t -n 1 oc get --show-kind --ignore-not-found


> start

oc apply -f -<<EOF
---
#STEP 00
apiVersion: v1
kind: Namespace
metadata:
  name: ${CLUSTER}

---
# STEP 01
kind: Secret
apiVersion: v1
metadata:
  name: bmc-${BARE_METAL_HOST}
  namespace: ${CLUSTER}
#  labels:
#    environment.metal3.io: baremetal
data:
  password: <to complet>
  username: <to complet>
type: Opaque

---
# STEP 01
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret-${HOST_INVENTORY}
  namespace: ${HOST_INVENTORY}
data:
  .dockerconfigjson: >-
<to complet>
type: kubernetes.io/dockerconfigjson

---
# STEP 02
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: ${HOST_INVENTORY}
  namespace: ${HOST_INVENTORY}
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    agentclusterinstalls.extensions.hive.openshift.io/location: ${HOST_INVENTORY_LOCATION}
    networkType: ${HOST_INVENTORY_NETWORKTYPE}    
spec:
#  proxy:
#    httpProxy: <proxy>
#    httpsProxy: <proxy>
#    noProxy: <domain-or-ips-comma-sepparated>
#  additionalNTPSources:
#    - 0.rhel.pool.ntp.org

  # clusterRef:
  #   name: ${CLUSTER}
  #   namespace: ${CLUSTER}
  agentLabels:
    agentclusterinstalls.extensions.hive.openshift.io/location: ${HOST_INVENTORY_LOCATION}
  cpuArchitecture: x86_64
  ipxeScriptType: DiscoveryImageAlways

  sshAuthorizedKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQCefCUYNfih7lQZJDd4hPZVlf5U4Kwc6DqAFQrKpD+rRrtRLJn5LVLIAa5pRE0xbl7cSsK5XqJVwQOtY9bXv6sdBmh7SHeMY61MOIrwZjDOZJuco6WYwBlCkMbzi/dcurFWcjIMc2N4fXnlrfWWRwBittoLktjwhlp6CpGy7SFoqrhXsX4Jb+aX12ZwgAGFV8laudjwE/Ou6aDMf6E/3kUbw7UOUkQ7Gzb8mRrdDuJtBK0ygRQGUoJYJydUfg5IqorwB59Omxj8GsqUH6xUud8VhlgvwYEnJXDngNvgoEhxa4vjv83vEIXoI8NZr7ft8ew9oaUmohSSG40mBYkzJUKDz/FO8zAjcW+JAWd2e/vPvYFzxXJ+uKVv/XKxsKB9oz9PQQG7OllT6DDlFORi6S75QjkqBgGGIbgRz6p93HCaRdA8Mc2J5/JYMZ/r/QHQG56rfZMEgYPIvgIDvSg3VtHJQp+oDCUCjMqFOU+Va2gqwV2RY8wPe7jkC7B3BFRzodpRP8Swm2rZSnJlp/ZAuD+FJv/OI3N2IqxFKXjnDR9ioUyvdFzmyEYpKheE7dtNpVGPyEVc3xhL69XgF4eDJvCAwVHjyn0ryR6Q3zFwUwurqRc60j+Myzikd1WD/5bv8fLYqcRLi+pEyAeAXZYWtpciW/V4xoVwXDKqy07j+ebBTGQblQZYEjH7J4zzpEFLdJekzhCWatmWx7kkq7LvE4Sa7SgVnaC+JMBPhcaWc2zEEyi8kMYpDVoRuRsxU0vtHfk5ZShGegzEfynnmabK/8YhDDXS5TVB1ycRndeDi+AkWVWZ9KsVdcHTImXM2x4SS1GxG5E9Fnw+1PdZ0YHbrpyyVr37/kVXy02hX8CunTYISFT7RVi+xEB5GfszX1tkzknBm/jd8bdAPUfSKWwuQEtqbk5emXexWrjAmKot6PUAY5NA1TFvgZCPEk6Uzla7lZGsMElee8sSy8IIBLLwpoMt5IpVuuo4csjxUD6vd9HrI6nS2Ms2UWuvL9Fv13WBb9sSh5uie92bk5sWE8yhYkPFzbZacV08OhMP8t/FepFlHuwEc/q+OWj51Zm54paLwTcuajpNaYZsvTarfPyLwxh5wk+1wZLlbvr1cPLEE/9BRFf1p+ab4jvtU9cXaN7BaUXJAXM4DnRLecG09APUH1QBPKuu9tL1wuSZvKIRav1TzO1DsMj/0F5grxTW3rcCUaqKqjUbbstLvfeph3W3RdRVxfEtqHlIwMi7gEzCB4lnL7Qn7rqyemWhagHqa9nyClCyDxG8tFXuaHtrRk1k/fbGxeDmQ5X4AbsXUqjRq095+cwF0Yr+t30YTOKLO5NA/WLJMYBQgh7ZkEMOLamrUdt1 lcolagio@MacBook-Pro'
  agentLabelSelector:
    matchLabels:
      cluster-name: ${CLUSTER}
  pullSecretRef:
    name: pull-secret-${HOST_INVENTORY}
  nmStateConfigLabelSelector:
    matchLabels:
      infraenvs.agent-install.openshift.io: ${HOST_INVENTORY}
# User for modify ignition during discovery
#  ignitionConfigOverride: ''

---
# STEP 04
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: bm5-ipstatic-${BARE_METAL_HOST}
  namespace: ${HOST_INVENTORY}
  labels:
    agent-install.openshift.io/bmh: ${BARE_METAL_HOST}
    infraenvs.agent-install.openshift.io: ${HOST_INVENTORY}
spec:
  config:
    dns-resolver:
      config:
        search:
          - redhat.hpecic.net
        server:
          - 10.11.0.13
    interfaces:
      - name: eno49
        state: down
        type: ethernet
      - ipv4:
          address:
            - ip: ${BARE_METAL_NETWORK_WORKLOAD_IP}
              prefix-length: 24
          dhcp: false
          enabled: true
        ipv6:
          enabled: false
        name: eno50
        state: up
        type: ethernet
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.6.82.1
          next-hop-interface: eno50
          table-id: 254
  interfaces:    
    - macAddress: ${BARE_METAL_NETWORK_PROVISION_MAC}
      name: eno49
    - macAddress: ${BARE_METAL_NETWORK_WORKLOAD_MAC}
      name: eno50


---
# STEP 03
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: ${BARE_METAL_HOST}
    inspect.metal3.io: disabled
  name: ${BARE_METAL_HOST}
  namespace: ${CLUSTER}
  labels:
    infraenvs.agent-install.openshift.io: ${HOST_INVENTORY}
spec:
  automatedCleaningMode: disabled
  bmc:
    address: ${BARE_METAL_BMC_IP}
    credentialsName: bmc-${BARE_METAL_HOST}
    disableCertificateVerification: true
  bootMACAddress: ${BARE_METAL_NETWORK_PROVISION_MAC}
  bootMode: UEFI
  description: ' '
  online: false

EOF
